name: scenarioshelf
version: 1.0.0+1
publish_to: none
description: TRPG通過シナリオ記録サービス

environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: 1.0.2
  flutter: 
    sdk: flutter

dev_dependencies:
  flutter_test: 
    sdk: flutter
  build_runner: 2.4.7
  flutter_lints: 2.0.0
  very_good_analysis: 5.1.0
  flutter_oss_licenses: 2.0.1
  import_sorter: 4.6.0
  
flutter: 
  uses-material-design: true
