name: scenarioshelf
version: 1.0.0+1
publish_to: none
description: TRPG通過シナリオ記録サービス

environment: 
  sdk: '>=3.2.3 <4.0.0'
  flutter: '3.19.6'

dependencies: 
  flutter: 
    sdk: flutter
  
  # Design
  cupertino_icons: 1.0.8
  google_fonts: 6.2.1
  shimmer: 3.0.0

  # BaaS
  supabase_flutter: 2.5.1
  firebase_core: 2.30.1
  firebase_analytics: 10.10.4
  firebase_crashlytics: 3.5.4
  firebase_auth: 4.19.4
  google_sign_in: 6.2.1
  cloud_firestore: 4.17.2

  # State Management
  flutter_hooks: 0.20.5
  hooks_riverpod: 2.5.1
  riverpod_annotation: 2.3.5
  freezed_annotation: 2.4.1

  # Other
  go_router: 14.0.1
  intl: 0.19.0
  logger: 2.2.0
  app_tracking_transparency: 2.0.5
  collection: 1.18.0
  flutter_dotenv: 5.1.0

dev_dependencies:
  flutter_test: 
    sdk: flutter
  
  # Generator
  build_runner: 2.4.9
  freezed: 2.5.2
  json_serializable: 6.8.0
  riverpod_generator: 2.4.0
  flutter_launcher_icons: 0.13.1
  flutter_oss_licenses: 3.0.2
  flutter_gen_runner: 5.4.0
  
  # Linter
  flutter_lints: 3.0.2
  custom_lint: 0.6.4
  very_good_analysis: 5.1.0
  riverpod_lint: 2.3.10
  
  # Other
  import_sorter: 4.6.0

  # build_runner の実行コマンド
  # flutter packages pub run build_runner build --delete-conflicting-outputs
  # flutter packages pub run build_runner watch --delete-conflicting-outputs

  # oss_licenses.dart の生成コマンド（パッケージを追加したら実行する）
  # flutter pub run flutter_oss_licenses:generate.dart -o lib/constants/oss_licenses.dart

flutter: 
  uses-material-design: true
  assets:
    - .env.dev
    - .env.stg
    - .env.prod
    - assets/images/logos/

import_sorter:
  comments: false
  ignored_files:
    - \/lib\/*\/*.freezed.dart
    - \/lib\/*\/*.g.dart
    - \/lib\/*\/oss_licenses.dart
    - \/lib\/*\/firebase_options.dart

  # 実行コマンド
  # flutter pub run import_sorter:main

flutter_icons:
  android: "launcher_icon"
  min_sdk_android: 21
  adaptive_icon_background: "#FFC966"
  ios: true
  remove_alpha_ios: true

  # 実行コマンド
  # flutter pub run flutter_launcher_icons:main

flutter_gen:
  output: lib/constants/assets/gen/
  line_length: 200

  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
    lottie: false
