-- Supabaseを停止しないように定期的に書き込みを行うためのテーブル
-- https://github.com/travisvn/supabase-inactive-fix?tab=readme-ov-file#supabase-database-setup
CREATE TABLE "keep-alive" (
  id BIGINT generated BY DEFAULT AS IDENTITY,
  name text NULL DEFAULT '':: text,
  random uuid NULL DEFAULT gen_random_uuid (),
  CONSTRAINT "keep-alive_pkey" PRIMARY key (id)
);

INSERT INTO
  "keep-alive"(name)
VALUES
  ('placeholder'),
  ('example');
